# Generated by Django 6.0 on 2025-12-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminApp", "0002_alter_categorydb_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductDb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "CategoryName",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("Product", models.CharField(blank=True, max_length=100, null=True)),
                ("Price", models.IntegerField(blank=True, null=True)),
                ("Brand", models.CharField(blank=True, null=True)),
                (
                    "Short_description",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "Detailed_description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "Image1",
                    models.ImageField(
                        blank=True, null=True, upload_to="Product images"
                    ),
                ),
            ],
        ),
    ]
