# Generated by Django 6.0 on 2025-12-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminApp", "0003_productdb"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdb",
            name="Image2",
            field=models.ImageField(blank=True, null=True, upload_to="Product images"),
        ),
        migrations.AddField(
            model_name="productdb",
            name="Image3",
            field=models.ImageField(blank=True, null=True, upload_to="Product images"),
        ),
    ]
