# Generated by Django 5.2.9 on 2025-12-31 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserDb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("User_name", models.CharField(max_length=100)),
                ("Email", models.EmailField(max_length=100)),
                ("Password", models.CharField(max_length=255)),
            ],
        ),
    ]
