# Generated by Django 5.2.9 on 2026-01-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WebApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Email", models.EmailField(max_length=100)),
                ("Subject", models.CharField(max_length=200)),
                ("Message", models.TextField(max_length=200)),
            ],
        ),
    ]
