# Generated by Django 5.2.9 on 2026-01-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("WebApp", "0002_contact"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Contact",
            new_name="ContactDb",
        ),
    ]
